// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSG4S8dQpYlgPKchflkeZb82GSpjDOXz8',
    appId: '1:1042486442359:web:683815b2e81b0e2a4f8972',
    messagingSenderId: '1042486442359',
    projectId: 'medicine-order-platform',
    authDomain: 'medicine-order-platform.firebaseapp.com',
    storageBucket: 'medicine-order-platform.appspot.com',
    measurementId: 'G-KR0YV1BD7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh0_1OrTfrBLPU42wDWom0odxC3G8qNsU',
    appId: '1:1042486442359:android:5ceff108b4910cc34f8972',
    messagingSenderId: '1042486442359',
    projectId: 'medicine-order-platform',
    storageBucket: 'medicine-order-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQOcx3MFhgL7eLtweSlBgVjsms2byYTaA',
    appId: '1:1042486442359:ios:8ab00e471ccfb72d4f8972',
    messagingSenderId: '1042486442359',
    projectId: 'medicine-order-platform',
    storageBucket: 'medicine-order-platform.appspot.com',
    iosClientId: '1042486442359-b1eotgd0gvj4g8g7mn951a7r2dn47pe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePharmaciePlatformApp',
  );
}
